INSERT INTO questions (content, options, weight) VALUES
('Je communique facilement avec mes collègues.', ARRAY['Oui', 'Non'], 1),
('Je suis à l''aise pour parler en public.', ARRAY['Oui', 'Non'], 1),
('Je sais m''exprimer clairement à l''écrit.', ARRAY['Oui', 'Non'], 1),
('Je suis à l''aise pour poser des questions si je ne comprends pas.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''exprimer avec assurance.', ARRAY['Oui', 'Non'], 1),
('Je sais garder mon calme face à un désaccord.', ARRAY['Oui', 'Non'], 1),
('Je respecte toujours les horaires convenus.', ARRAY['Oui', 'Non'], 1),
('Je sais organiser mon temps de travail efficacement.', ARRAY['Oui', 'Non'], 1),
('Je respecte les délais qui me sont fixés.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de prioriser mes tâches efficacement.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de gérer plusieurs tâches en même temps.', ARRAY['Oui', 'Non'], 1),
('Je fais preuve de rigueur dans mon travail.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''organiser sans supervision constante.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''adapter rapidement à un nouvel environnement.', ARRAY['Oui', 'Non'], 1),
('J''accepte volontiers les critiques constructives.', ARRAY['Oui', 'Non'], 1),
('Je reste calme dans les situations stressantes.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de travailler sous pression.', ARRAY['Oui', 'Non'], 1),
('Je m''adapte facilement aux changements d''organisation.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de gérer un imprévu sans paniquer.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à sortir de ma zone de confort.', ARRAY['Oui', 'Non'], 1);