INSERT INTO questions (content, options, weight) VALUES
('Je respecte toujours les horaires convenus.', ARRAY['Oui', 'Non'], 1),
('J''aime travailler en équipe.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''adapter rapidement à un nouvel environnement.', ARRAY['Oui', 'Non'], 1),
('Je termine toujours ce que je commence.', ARRAY['Oui', 'Non'], 1),
('Je sais demander de l''aide quand j''en ai besoin.', ARRAY['Oui', 'Non'], 1),
('J''accepte volontiers les critiques constructives.', ARRAY['Oui', 'Non'], 1),
('Je me fixe des objectifs clairs dans mon travail.', ARRAY['Oui', 'Non'], 1),
('J''aime relever de nouveaux défis.', ARRAY['Oui', 'Non'], 1),
('Je reste motivé même face à des tâches répétitives.', ARRAY['Oui', 'Non'], 1),
('Je communique facilement avec mes collègues.', ARRAY['Oui', 'Non'], 1),
('Je respecte les règles et procédures de l''entreprise.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de gérer plusieurs tâches en même temps.', ARRAY['Oui', 'Non'], 1),
('Je prends des initiatives sans qu''on me le demande.', ARRAY['Oui', 'Non'], 1),
('Je reste calme dans les situations stressantes.', ARRAY['Oui', 'Non'], 1),
('J''aime apprendre de nouvelles compétences.', ARRAY['Oui', 'Non'], 1),
('Je suis ponctuel(le) à mes rendez-vous professionnels.', ARRAY['Oui', 'Non'], 1),
('Je sais organiser mon temps de travail efficacement.', ARRAY['Oui', 'Non'], 1),
('Je suis honnête avec mes collègues et supérieurs.', ARRAY['Oui', 'Non'], 1),
('J''aime aider les autres dans leur travail.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de travailler de façon autonome.', ARRAY['Oui', 'Non'], 1),
('Je respecte les délais qui me sont fixés.', ARRAY['Oui', 'Non'], 1),
('Je suis à l''aise pour parler en public.', ARRAY['Oui', 'Non'], 1),
('Je sais reconnaître mes erreurs et en tirer des leçons.', ARRAY['Oui', 'Non'], 1),
('J''aime avoir des responsabilités.', ARRAY['Oui', 'Non'], 1),
('Je m''implique pleinement dans les projets qu''on me confie.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de résoudre des problèmes de façon autonome.', ARRAY['Oui', 'Non'], 1),
('Je m''entends généralement bien avec mes collègues.', ARRAY['Oui', 'Non'], 1),
('Je suis motivé(e) par l''idée de progresser professionnellement.', ARRAY['Oui', 'Non'], 1),
('Je fais preuve de patience face aux difficultés.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à sortir de ma zone de confort.', ARRAY['Oui', 'Non'], 1),
('Je sais garder la confidentialité des informations sensibles.', ARRAY['Oui', 'Non'], 1),
('Je m''adapte facilement aux changements d''organisation.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de prioriser mes tâches efficacement.', ARRAY['Oui', 'Non'], 1),
('Je fais preuve de rigueur dans mon travail.', ARRAY['Oui', 'Non'], 1),
('J''aime partager mes connaissances avec les autres.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de travailler sous pression.', ARRAY['Oui', 'Non'], 1),
('Je respecte les opinions différentes des miennes.', ARRAY['Oui', 'Non'], 1),
('Je sais rester professionnel(le) en toute circonstance.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à faire des efforts supplémentaires si nécessaire.', ARRAY['Oui', 'Non'], 1),
('Je crois en l''importance du travail bien fait.', ARRAY['Oui', 'Non'], 1),
('Je suis quelqu''un de fiable sur qui on peut compter.', ARRAY['Oui', 'Non'], 1),
('J''aime comprendre le sens de mon travail.', ARRAY['Oui', 'Non'], 1),
('Je sais m''exprimer clairement à l''écrit.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''auto-évaluer objectivement.', ARRAY['Oui', 'Non'], 1),
('Je respecte la hiérarchie tout en donnant mon avis.', ARRAY['Oui', 'Non'], 1),
('Je suis motivé(e) à long terme dans mes projets.', ARRAY['Oui', 'Non'], 1),
('Je sais garder mon calme face à un désaccord.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''organiser sans supervision constante.', ARRAY['Oui', 'Non'], 1),
('J''aime travailler dans un environnement structuré.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à me former pour évoluer dans mon métier.', ARRAY['Oui', 'Non'], 1),
('Je considère l''honnêteté comme une valeur essentielle au travail.', ARRAY['Oui', 'Non'], 1),
('Je sais m''entourer de personnes compétentes.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de gérer une charge de travail importante.', ARRAY['Oui', 'Non'], 1),
('J''aime comprendre les attentes avant de commencer une tâche.', ARRAY['Oui', 'Non'], 1),
('Je fais preuve de persévérance face à l''échec.', ARRAY['Oui', 'Non'], 1),
('Je respecte le travail et le temps des autres.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''intégrer rapidement dans une équipe.', ARRAY['Oui', 'Non'], 1),
('Je considère la ponctualité comme importante.', ARRAY['Oui', 'Non'], 1),
('Je suis motivé(e) par l''atteinte d''objectifs concrets.', ARRAY['Oui', 'Non'], 1),
('Je sais accepter de ne pas toujours avoir raison.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de rester concentré(e) longtemps sur une tâche.', ARRAY['Oui', 'Non'], 1),
('J''aime contribuer à un objectif commun.', ARRAY['Oui', 'Non'], 1),
('Je suis à l''aise pour poser des questions si je ne comprends pas.', ARRAY['Oui', 'Non'], 1),
('Je considère le respect mutuel comme fondamental au travail.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''adapter à différents interlocuteurs.', ARRAY['Oui', 'Non'], 1),
('Je sais gérer mon stress avant une échéance importante.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à changer d''avis si les arguments sont convaincants.', ARRAY['Oui', 'Non'], 1),
('J''aime avoir un cadre de travail clair.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de proposer des solutions à un problème.', ARRAY['Oui', 'Non'], 1),
('Je considère la loyauté comme une valeur importante.', ARRAY['Oui', 'Non'], 1),
('Je sais travailler avec des personnes différentes de moi.', ARRAY['Oui', 'Non'], 1),
('Je suis motivé(e) à me dépasser dans mon travail.', ARRAY['Oui', 'Non'], 1),
('Je respecte les engagements que je prends.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de gérer une déception professionnelle.', ARRAY['Oui', 'Non'], 1),
('J''aime comprendre le fonctionnement global d''une entreprise.', ARRAY['Oui', 'Non'], 1),
('Je considère la transparence comme essentielle.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''exprimer avec assurance.', ARRAY['Oui', 'Non'], 1),
('Je sais reconnaître le travail des autres.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à m''investir sur le long terme.', ARRAY['Oui', 'Non'], 1),
('Je considère l''esprit d''équipe comme indispensable.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''auto-discipliner.', ARRAY['Oui', 'Non'], 1),
('J''aime avoir un retour sur la qualité de mon travail.', ARRAY['Oui', 'Non'], 1),
('Je suis motivé(e) par le sentiment d''utilité.', ARRAY['Oui', 'Non'], 1),
('Je respecte les valeurs de l''entreprise qui m''emploie.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de gérer un imprévu sans paniquer.', ARRAY['Oui', 'Non'], 1),
('Je considère le respect des délais comme une priorité.', ARRAY['Oui', 'Non'], 1),
('Je sais m''adapter à un rythme de travail soutenu.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de collaborer avec des services différents.', ARRAY['Oui', 'Non'], 1),
('J''aime que mon travail ait un impact concret.', ARRAY['Oui', 'Non'], 1),
('Je considère l''écoute comme une qualité essentielle.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à accepter des tâches en dehors de mes attributions habituelles.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de faire preuve de diplomatie.', ARRAY['Oui', 'Non'], 1),
('Je considère la motivation comme un moteur essentiel de la réussite.', ARRAY['Oui', 'Non'], 1),
('Je sais garder une attitude positive face aux difficultés.', ARRAY['Oui', 'Non'], 1),
('Je suis capable de m''engager pleinement dans un projet.', ARRAY['Oui', 'Non'], 1),
('Je considère le sérieux comme une qualité professionnelle clé.', ARRAY['Oui', 'Non'], 1),
('Je suis motivé(e) à l''idée de rejoindre une nouvelle équipe.', ARRAY['Oui', 'Non'], 1),
('Je considère que le travail bien fait mérite d''être reconnu.', ARRAY['Oui', 'Non'], 1),
('Je suis prêt(e) à donner le meilleur de moi-même au travail.', ARRAY['Oui', 'Non'], 1),
('Je considère que le respect des consignes est important.', ARRAY['Oui', 'Non'], 1);
