INSERT INTO profiles (name, email, password_hash, date_of_birth, skills, sector, location, video_url) VALUES
('Amina Bensaid', 'amina.bensaid@email.com', '$2a$10$examplehashedpassword01', '1996-02-14', ARRAY['Comptabilité', 'Excel', 'SAP'], 'Finance', 'Strasbourg', 'https://www.youtube.com/watch?v=dQw4w9WgXcQ'),
('Thomas Lefèvre', 'thomas.lefevre@email.com', '$2a$10$examplehashedpassword02', '1994-06-30', ARRAY['Java', 'Spring Boot', 'Kubernetes'], 'Tech', 'Lille', 'https://vimeo.com/76979871'),
('Chloé Girard', 'chloe.girard@email.com', '$2a$10$examplehashedpassword03', '2001-01-09', ARRAY['Illustration', 'Adobe Illustrator', 'Storyboard'], 'Design', 'Rennes', 'https://www.youtube.com/watch?v=aqz-KE-bpKQ'),
('Yanis Meziane', 'yanis.meziane@email.com', '$2a$10$examplehashedpassword04', '1998-10-21', ARRAY['Vente B2B', 'Négociation', 'CRM'], 'Commerce', 'Toulouse', 'https://vimeo.com/148751763'),
('Sarah Dubois', 'sarah.dubois@email.com', '$2a$10$examplehashedpassword05', '1997-04-03', ARRAY['Ressources humaines', 'Recrutement', 'Droit du travail'], 'RH', 'Nantes', 'https://www.youtube.com/watch?v=jNQXAC9IVRw'),
('Hugo Faure', 'hugo.faure@email.com', '$2a$10$examplehashedpassword06', '1993-12-17', ARRAY['Électricité', 'Domotique', 'Sécurité incendie'], 'BTP', 'Marseille', 'https://vimeo.com/22439234'),
('Inès Chevalier', 'ines.chevalier@email.com', '$2a$10$examplehashedpassword07', '1999-08-25', ARRAY['Rédaction web', 'SEO', 'WordPress'], 'Communication', 'Montpellier', 'https://www.youtube.com/watch?v=eYq7WapuDLU'),
('Nathan Roux', 'nathan.roux@email.com', '$2a$10$examplehashedpassword08', '1995-03-11', ARRAY['DevOps', 'AWS', 'Terraform'], 'Tech', 'Grenoble', 'https://vimeo.com/336812686'),
('Lina Benali', 'lina.benali@email.com', '$2a$10$examplehashedpassword09', '2000-05-06', ARRAY['Traduction', 'Anglais', 'Espagnol'], 'Éducation', 'Nice', 'https://www.youtube.com/watch?v=3JZ_D3ELwOQ'),
('Enzo Marchand', 'enzo.marchand@email.com', '$2a$10$examplehashedpassword10', '1996-09-19', ARRAY['Logistique', 'Gestion de stock', 'SAP'], 'Logistique', 'Le Havre', 'https://vimeo.com/259411563'),
('Camille Perrot', 'camille.perrot@email.com', '$2a$10$examplehashedpassword11', '1998-07-02', ARRAY['Comptabilité', 'Paie', 'Sage'], 'Finance', 'Rouen', 'https://www.youtube.com/watch?v=hFcLyDb6niA'),
('Adam Rahmouni', 'adam.rahmouni@email.com', '$2a$10$examplehashedpassword12', '1994-11-28', ARRAY['Cuisine', 'Pâtisserie', 'HACCP'], 'Restauration', 'Lyon', 'https://vimeo.com/94338566'),
('Manon Fontaine', 'manon.fontaine@email.com', '$2a$10$examplehashedpassword13', '2002-02-15', ARRAY['UX Research', 'Figma', 'Tests utilisateurs'], 'Design', 'Bordeaux', 'https://www.youtube.com/watch?v=09R8_2nJtjg'),
('Lucas Berger', 'lucas.berger@email.com', '$2a$10$examplehashedpassword14', '1997-01-08', ARRAY['Data Engineering', 'Python', 'Airflow'], 'Data', 'Paris', 'https://vimeo.com/45196609'),
('Emma Lambert', 'emma.lambert@email.com', '$2a$10$examplehashedpassword15', '1999-06-13', ARRAY['Assistance sociale', 'Écoute active', 'Médiation'], 'Social', 'Strasbourg', 'https://www.youtube.com/watch?v=YykjpeuMNEk'),
('Baptiste Morel', 'baptiste.morel@email.com', '$2a$10$examplehashedpassword16', '1995-10-04', ARRAY['Mécanique auto', 'Diagnostic électronique', 'Soudure'], 'Industrie', 'Metz', 'https://vimeo.com/110680044'),
('Léa Simon', 'lea.simon@email.com', '$2a$10$examplehashedpassword17', '2000-12-22', ARRAY['Community management', 'Réseaux sociaux', 'Canva'], 'Marketing', 'Nantes', 'https://www.youtube.com/watch?v=8UVNT4wvIGY'),
('Rayan Cherif', 'rayan.cherif@email.com', '$2a$10$examplehashedpassword18', '1996-04-17', ARRAY['Cybersécurité', 'Pentest', 'Linux'], 'Tech', 'Toulouse', 'https://vimeo.com/196279302'),
('Julie Renard', 'julie.renard@email.com', '$2a$10$examplehashedpassword19', '1998-08-09', ARRAY['Gestion de projet', 'Scrum', 'Jira'], 'Management', 'Lyon', 'https://www.youtube.com/watch?v=L_jWHffIx5E'),
('Maxime Petit', 'maxime.petit@email.com', '$2a$10$examplehashedpassword20', '1993-05-27', ARRAY['Électrotechnique', 'Automatisme', 'Habilitation électrique'], 'Industrie', 'Dijon', 'https://vimeo.com/39197923');
